server:
  port: 8080

spring:
  #  datasource:
  #    url: jdbc:mysql://localhost:3308/test?useUnicode=true&amp&characterEncoding=utf-8&amp&serverTimezone=UTC #注意设置编码格式及时区
  #    username: root
  #    password: 123456
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3308/test?useUnicode=true&amp&characterEncoding=utf-8&amp&serverTimezone=UTC #注意设置编码格式及时区
    username: root
    password: 123456
    initialSize: 3
    minidle: 3
    maxActive: 18
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM dual
    filters: stat,wall,log4j
mybatis:
  mapper-locations: classpath*:mybatis/*.xml
logging:
  #  config: classpath:log4j2.yml
  file: /log/apilog.log